### ISSUE TITLE
Multiselect Dropdown not shown in End-User Portal

### ISSUE THREAD

**Issue by KristinBl** [freescout-help-desk/freescout#4399]
Hi there, 

i am using the custom fields module in combination with the end-user portal module to create a simple form. Sadly, when adding a multiselect dropdown field it is not correctly rendered and shows a single line text input instead. The normal "single select" dropdowns are working fine. Any help would be appreciated.

**Comment by freescout-help** [comment]
Are you using the latest version of FreeScout and End-User Portal Module?
Can you reproduce the issue on demo.freescout.net?

**Comment by KristinBl** [comment]
Yes, I am using the latest versions (1.8.159 and 1.0.87 respectively) and can reproduce the issue on the demo server. I am adding a few screenshots from the demo server to illustrate: 

![Bildschirmfoto 2024-12-05 um 09 18 09](https://github.com/user-attachments/assets/c4bdd5ff-ab98-4a9e-a496-dab6e10d4e35)
![Bildschirmfoto 2024-12-05 um 09 18 18](https://github.com/user-attachments/assets/c187a79a-595a-4b76-8216-96c84d4d7441)
![Bildschirmfoto 2024-12-05 um 09 18 32](https://github.com/user-attachments/assets/e5a70cf8-d6dc-4d74-b467-f2c76ca45c7d)

**Comment by freescout-help** [comment]
Fixed in End-User Portal Module v1.0.88

And keep in mind that If you are adding Multiselect custom field to the Contact Form this field won't autosuggest values like it happens when you are entering values in conversations in FreeScout. It's done not to expose to customers all the existing values you have in this field in your system.

**Comment by KristinBl** [comment]
Thank you very much for the quick fix!
